// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Security.proto

// Protobuf Java Version: 3.25.1
package com.security;

public final class HelloSecurityProto {
  private HelloSecurityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SecurityRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SecurityRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string onInstructs = 1;</code>
     * @return The onInstructs.
     */
    String getOnInstructs();
    /**
     * <code>string onInstructs = 1;</code>
     * @return The bytes for onInstructs.
     */
    com.google.protobuf.ByteString
        getOnInstructsBytes();

    /**
     * <code>string offInstructs = 2;</code>
     * @return The offInstructs.
     */
    String getOffInstructs();
    /**
     * <code>string offInstructs = 2;</code>
     * @return The bytes for offInstructs.
     */
    com.google.protobuf.ByteString
        getOffInstructsBytes();
  }
  /**
   * Protobuf type {@code SecurityRequest}
   */
  public static final class SecurityRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SecurityRequest)
      SecurityRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SecurityRequest.newBuilder() to construct.
    private SecurityRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SecurityRequest() {
      onInstructs_ = "";
      offInstructs_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SecurityRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloSecurityProto.internal_static_SecurityRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloSecurityProto.internal_static_SecurityRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SecurityRequest.class, Builder.class);
    }

    public static final int ONINSTRUCTS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object onInstructs_ = "";
    /**
     * <code>string onInstructs = 1;</code>
     * @return The onInstructs.
     */
    @Override
    public String getOnInstructs() {
      Object ref = onInstructs_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        onInstructs_ = s;
        return s;
      }
    }
    /**
     * <code>string onInstructs = 1;</code>
     * @return The bytes for onInstructs.
     */
    @Override
    public com.google.protobuf.ByteString
        getOnInstructsBytes() {
      Object ref = onInstructs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        onInstructs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFINSTRUCTS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object offInstructs_ = "";
    /**
     * <code>string offInstructs = 2;</code>
     * @return The offInstructs.
     */
    @Override
    public String getOffInstructs() {
      Object ref = offInstructs_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        offInstructs_ = s;
        return s;
      }
    }
    /**
     * <code>string offInstructs = 2;</code>
     * @return The bytes for offInstructs.
     */
    @Override
    public com.google.protobuf.ByteString
        getOffInstructsBytes() {
      Object ref = offInstructs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        offInstructs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onInstructs_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, onInstructs_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(offInstructs_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, offInstructs_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(onInstructs_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, onInstructs_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(offInstructs_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, offInstructs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SecurityRequest)) {
        return super.equals(obj);
      }
      SecurityRequest other = (SecurityRequest) obj;

      if (!getOnInstructs()
          .equals(other.getOnInstructs())) return false;
      if (!getOffInstructs()
          .equals(other.getOffInstructs())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ONINSTRUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getOnInstructs().hashCode();
      hash = (37 * hash) + OFFINSTRUCTS_FIELD_NUMBER;
      hash = (53 * hash) + getOffInstructs().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SecurityRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SecurityRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SecurityRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SecurityRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SecurityRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SecurityRequest)
        SecurityRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloSecurityProto.internal_static_SecurityRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloSecurityProto.internal_static_SecurityRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SecurityRequest.class, Builder.class);
      }

      // Construct using com.security.HelloSecurityProto.SecurityRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        onInstructs_ = "";
        offInstructs_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloSecurityProto.internal_static_SecurityRequest_descriptor;
      }

      @Override
      public SecurityRequest getDefaultInstanceForType() {
        return SecurityRequest.getDefaultInstance();
      }

      @Override
      public SecurityRequest build() {
        SecurityRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SecurityRequest buildPartial() {
        SecurityRequest result = new SecurityRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SecurityRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.onInstructs_ = onInstructs_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.offInstructs_ = offInstructs_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SecurityRequest) {
          return mergeFrom((SecurityRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SecurityRequest other) {
        if (other == SecurityRequest.getDefaultInstance()) return this;
        if (!other.getOnInstructs().isEmpty()) {
          onInstructs_ = other.onInstructs_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getOffInstructs().isEmpty()) {
          offInstructs_ = other.offInstructs_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                onInstructs_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                offInstructs_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object onInstructs_ = "";
      /**
       * <code>string onInstructs = 1;</code>
       * @return The onInstructs.
       */
      public String getOnInstructs() {
        Object ref = onInstructs_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          onInstructs_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string onInstructs = 1;</code>
       * @return The bytes for onInstructs.
       */
      public com.google.protobuf.ByteString
          getOnInstructsBytes() {
        Object ref = onInstructs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          onInstructs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string onInstructs = 1;</code>
       * @param value The onInstructs to set.
       * @return This builder for chaining.
       */
      public Builder setOnInstructs(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        onInstructs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string onInstructs = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnInstructs() {
        onInstructs_ = getDefaultInstance().getOnInstructs();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string onInstructs = 1;</code>
       * @param value The bytes for onInstructs to set.
       * @return This builder for chaining.
       */
      public Builder setOnInstructsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        onInstructs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object offInstructs_ = "";
      /**
       * <code>string offInstructs = 2;</code>
       * @return The offInstructs.
       */
      public String getOffInstructs() {
        Object ref = offInstructs_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          offInstructs_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string offInstructs = 2;</code>
       * @return The bytes for offInstructs.
       */
      public com.google.protobuf.ByteString
          getOffInstructsBytes() {
        Object ref = offInstructs_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          offInstructs_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string offInstructs = 2;</code>
       * @param value The offInstructs to set.
       * @return This builder for chaining.
       */
      public Builder setOffInstructs(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        offInstructs_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string offInstructs = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOffInstructs() {
        offInstructs_ = getDefaultInstance().getOffInstructs();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string offInstructs = 2;</code>
       * @param value The bytes for offInstructs to set.
       * @return This builder for chaining.
       */
      public Builder setOffInstructsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        offInstructs_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SecurityRequest)
    }

    // @@protoc_insertion_point(class_scope:SecurityRequest)
    private static final SecurityRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SecurityRequest();
    }

    public static SecurityRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SecurityRequest>
        PARSER = new com.google.protobuf.AbstractParser<SecurityRequest>() {
      @Override
      public SecurityRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SecurityRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SecurityRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public SecurityRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SecurityResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SecurityResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string warnings = 1;</code>
     * @return The warnings.
     */
    String getWarnings();
    /**
     * <code>string warnings = 1;</code>
     * @return The bytes for warnings.
     */
    com.google.protobuf.ByteString
        getWarningsBytes();

    /**
     * <code>string operations = 2;</code>
     * @return The operations.
     */
    String getOperations();
    /**
     * <code>string operations = 2;</code>
     * @return The bytes for operations.
     */
    com.google.protobuf.ByteString
        getOperationsBytes();

    /**
     * <code>string dangerRemove = 3;</code>
     * @return The dangerRemove.
     */
    String getDangerRemove();
    /**
     * <code>string dangerRemove = 3;</code>
     * @return The bytes for dangerRemove.
     */
    com.google.protobuf.ByteString
        getDangerRemoveBytes();

    /**
     * <code>string operationsTwo = 4;</code>
     * @return The operationsTwo.
     */
    String getOperationsTwo();
    /**
     * <code>string operationsTwo = 4;</code>
     * @return The bytes for operationsTwo.
     */
    com.google.protobuf.ByteString
        getOperationsTwoBytes();
  }
  /**
   * Protobuf type {@code SecurityResponse}
   */
  public static final class SecurityResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SecurityResponse)
      SecurityResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SecurityResponse.newBuilder() to construct.
    private SecurityResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SecurityResponse() {
      warnings_ = "";
      operations_ = "";
      dangerRemove_ = "";
      operationsTwo_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new SecurityResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloSecurityProto.internal_static_SecurityResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloSecurityProto.internal_static_SecurityResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SecurityResponse.class, Builder.class);
    }

    public static final int WARNINGS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object warnings_ = "";
    /**
     * <code>string warnings = 1;</code>
     * @return The warnings.
     */
    @Override
    public String getWarnings() {
      Object ref = warnings_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        warnings_ = s;
        return s;
      }
    }
    /**
     * <code>string warnings = 1;</code>
     * @return The bytes for warnings.
     */
    @Override
    public com.google.protobuf.ByteString
        getWarningsBytes() {
      Object ref = warnings_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        warnings_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object operations_ = "";
    /**
     * <code>string operations = 2;</code>
     * @return The operations.
     */
    @Override
    public String getOperations() {
      Object ref = operations_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operations_ = s;
        return s;
      }
    }
    /**
     * <code>string operations = 2;</code>
     * @return The bytes for operations.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperationsBytes() {
      Object ref = operations_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operations_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DANGERREMOVE_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object dangerRemove_ = "";
    /**
     * <code>string dangerRemove = 3;</code>
     * @return The dangerRemove.
     */
    @Override
    public String getDangerRemove() {
      Object ref = dangerRemove_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        dangerRemove_ = s;
        return s;
      }
    }
    /**
     * <code>string dangerRemove = 3;</code>
     * @return The bytes for dangerRemove.
     */
    @Override
    public com.google.protobuf.ByteString
        getDangerRemoveBytes() {
      Object ref = dangerRemove_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        dangerRemove_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPERATIONSTWO_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile Object operationsTwo_ = "";
    /**
     * <code>string operationsTwo = 4;</code>
     * @return The operationsTwo.
     */
    @Override
    public String getOperationsTwo() {
      Object ref = operationsTwo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operationsTwo_ = s;
        return s;
      }
    }
    /**
     * <code>string operationsTwo = 4;</code>
     * @return The bytes for operationsTwo.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperationsTwoBytes() {
      Object ref = operationsTwo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operationsTwo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warnings_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, warnings_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operations_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, operations_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dangerRemove_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dangerRemove_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationsTwo_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, operationsTwo_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(warnings_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, warnings_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operations_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, operations_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dangerRemove_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dangerRemove_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationsTwo_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, operationsTwo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof SecurityResponse)) {
        return super.equals(obj);
      }
      SecurityResponse other = (SecurityResponse) obj;

      if (!getWarnings()
          .equals(other.getWarnings())) return false;
      if (!getOperations()
          .equals(other.getOperations())) return false;
      if (!getDangerRemove()
          .equals(other.getDangerRemove())) return false;
      if (!getOperationsTwo()
          .equals(other.getOperationsTwo())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WARNINGS_FIELD_NUMBER;
      hash = (53 * hash) + getWarnings().hashCode();
      hash = (37 * hash) + OPERATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOperations().hashCode();
      hash = (37 * hash) + DANGERREMOVE_FIELD_NUMBER;
      hash = (53 * hash) + getDangerRemove().hashCode();
      hash = (37 * hash) + OPERATIONSTWO_FIELD_NUMBER;
      hash = (53 * hash) + getOperationsTwo().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static SecurityResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SecurityResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SecurityResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static SecurityResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static SecurityResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static SecurityResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static SecurityResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(SecurityResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SecurityResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SecurityResponse)
        SecurityResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloSecurityProto.internal_static_SecurityResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloSecurityProto.internal_static_SecurityResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SecurityResponse.class, Builder.class);
      }

      // Construct using com.security.HelloSecurityProto.SecurityResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        warnings_ = "";
        operations_ = "";
        dangerRemove_ = "";
        operationsTwo_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloSecurityProto.internal_static_SecurityResponse_descriptor;
      }

      @Override
      public SecurityResponse getDefaultInstanceForType() {
        return SecurityResponse.getDefaultInstance();
      }

      @Override
      public SecurityResponse build() {
        SecurityResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public SecurityResponse buildPartial() {
        SecurityResponse result = new SecurityResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(SecurityResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.warnings_ = warnings_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.operations_ = operations_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.dangerRemove_ = dangerRemove_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.operationsTwo_ = operationsTwo_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SecurityResponse) {
          return mergeFrom((SecurityResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SecurityResponse other) {
        if (other == SecurityResponse.getDefaultInstance()) return this;
        if (!other.getWarnings().isEmpty()) {
          warnings_ = other.warnings_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getOperations().isEmpty()) {
          operations_ = other.operations_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDangerRemove().isEmpty()) {
          dangerRemove_ = other.dangerRemove_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getOperationsTwo().isEmpty()) {
          operationsTwo_ = other.operationsTwo_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                warnings_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                operations_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                dangerRemove_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                operationsTwo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object warnings_ = "";
      /**
       * <code>string warnings = 1;</code>
       * @return The warnings.
       */
      public String getWarnings() {
        Object ref = warnings_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          warnings_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string warnings = 1;</code>
       * @return The bytes for warnings.
       */
      public com.google.protobuf.ByteString
          getWarningsBytes() {
        Object ref = warnings_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          warnings_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string warnings = 1;</code>
       * @param value The warnings to set.
       * @return This builder for chaining.
       */
      public Builder setWarnings(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        warnings_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string warnings = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWarnings() {
        warnings_ = getDefaultInstance().getWarnings();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string warnings = 1;</code>
       * @param value The bytes for warnings to set.
       * @return This builder for chaining.
       */
      public Builder setWarningsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        warnings_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object operations_ = "";
      /**
       * <code>string operations = 2;</code>
       * @return The operations.
       */
      public String getOperations() {
        Object ref = operations_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          operations_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string operations = 2;</code>
       * @return The bytes for operations.
       */
      public com.google.protobuf.ByteString
          getOperationsBytes() {
        Object ref = operations_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          operations_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operations = 2;</code>
       * @param value The operations to set.
       * @return This builder for chaining.
       */
      public Builder setOperations(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        operations_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string operations = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperations() {
        operations_ = getDefaultInstance().getOperations();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string operations = 2;</code>
       * @param value The bytes for operations to set.
       * @return This builder for chaining.
       */
      public Builder setOperationsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        operations_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object dangerRemove_ = "";
      /**
       * <code>string dangerRemove = 3;</code>
       * @return The dangerRemove.
       */
      public String getDangerRemove() {
        Object ref = dangerRemove_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          dangerRemove_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string dangerRemove = 3;</code>
       * @return The bytes for dangerRemove.
       */
      public com.google.protobuf.ByteString
          getDangerRemoveBytes() {
        Object ref = dangerRemove_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          dangerRemove_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dangerRemove = 3;</code>
       * @param value The dangerRemove to set.
       * @return This builder for chaining.
       */
      public Builder setDangerRemove(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        dangerRemove_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string dangerRemove = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDangerRemove() {
        dangerRemove_ = getDefaultInstance().getDangerRemove();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string dangerRemove = 3;</code>
       * @param value The bytes for dangerRemove to set.
       * @return This builder for chaining.
       */
      public Builder setDangerRemoveBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dangerRemove_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private Object operationsTwo_ = "";
      /**
       * <code>string operationsTwo = 4;</code>
       * @return The operationsTwo.
       */
      public String getOperationsTwo() {
        Object ref = operationsTwo_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          operationsTwo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string operationsTwo = 4;</code>
       * @return The bytes for operationsTwo.
       */
      public com.google.protobuf.ByteString
          getOperationsTwoBytes() {
        Object ref = operationsTwo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          operationsTwo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operationsTwo = 4;</code>
       * @param value The operationsTwo to set.
       * @return This builder for chaining.
       */
      public Builder setOperationsTwo(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        operationsTwo_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string operationsTwo = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationsTwo() {
        operationsTwo_ = getDefaultInstance().getOperationsTwo();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string operationsTwo = 4;</code>
       * @param value The bytes for operationsTwo to set.
       * @return This builder for chaining.
       */
      public Builder setOperationsTwoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        operationsTwo_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SecurityResponse)
    }

    // @@protoc_insertion_point(class_scope:SecurityResponse)
    private static final SecurityResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SecurityResponse();
    }

    public static SecurityResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SecurityResponse>
        PARSER = new com.google.protobuf.AbstractParser<SecurityResponse>() {
      @Override
      public SecurityResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<SecurityResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<SecurityResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public SecurityResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SecurityRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SecurityRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SecurityResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SecurityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Security.proto\"<\n\017SecurityRequest\022\023\n\013o" +
      "nInstructs\030\001 \001(\t\022\024\n\014offInstructs\030\002 \001(\t\"e" +
      "\n\020SecurityResponse\022\020\n\010warnings\030\001 \001(\t\022\022\n\n" +
      "operations\030\002 \001(\t\022\024\n\014dangerRemove\030\003 \001(\t\022\025" +
      "\n\roperationsTwo\030\004 \001(\t2K\n\rHelloSecurity\022:" +
      "\n\017securityService\022\020.SecurityRequest\032\021.Se" +
      "curityResponse(\0010\001B$\n\014com.securityB\022Hell" +
      "oSecurityProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SecurityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SecurityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SecurityRequest_descriptor,
        new String[] { "OnInstructs", "OffInstructs", });
    internal_static_SecurityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SecurityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SecurityResponse_descriptor,
        new String[] { "Warnings", "Operations", "DangerRemove", "OperationsTwo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
