// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Temperature.proto

// Protobuf Java Version: 3.25.1
package com.temperature;

public final class HelloTemperatureProto {
  private HelloTemperatureProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TemperatureRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TemperatureRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string tempCall = 1;</code>
     * @return The tempCall.
     */
    String getTempCall();
    /**
     * <code>string tempCall = 1;</code>
     * @return The bytes for tempCall.
     */
    com.google.protobuf.ByteString
        getTempCallBytes();
  }
  /**
   * Protobuf type {@code TemperatureRequest}
   */
  public static final class TemperatureRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TemperatureRequest)
      TemperatureRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TemperatureRequest.newBuilder() to construct.
    private TemperatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TemperatureRequest() {
      tempCall_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TemperatureRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloTemperatureProto.internal_static_TemperatureRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloTemperatureProto.internal_static_TemperatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TemperatureRequest.class, Builder.class);
    }

    public static final int TEMPCALL_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object tempCall_ = "";
    /**
     * <code>string tempCall = 1;</code>
     * @return The tempCall.
     */
    @Override
    public String getTempCall() {
      Object ref = tempCall_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tempCall_ = s;
        return s;
      }
    }
    /**
     * <code>string tempCall = 1;</code>
     * @return The bytes for tempCall.
     */
    @Override
    public com.google.protobuf.ByteString
        getTempCallBytes() {
      Object ref = tempCall_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tempCall_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tempCall_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tempCall_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tempCall_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tempCall_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TemperatureRequest)) {
        return super.equals(obj);
      }
      TemperatureRequest other = (TemperatureRequest) obj;

      if (!getTempCall()
          .equals(other.getTempCall())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEMPCALL_FIELD_NUMBER;
      hash = (53 * hash) + getTempCall().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TemperatureRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemperatureRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemperatureRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemperatureRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemperatureRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemperatureRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemperatureRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TemperatureRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static TemperatureRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static TemperatureRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TemperatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TemperatureRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TemperatureRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TemperatureRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TemperatureRequest)
        TemperatureRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloTemperatureProto.internal_static_TemperatureRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloTemperatureProto.internal_static_TemperatureRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TemperatureRequest.class, Builder.class);
      }

      // Construct using com.temperature.HelloTemperatureProto.TemperatureRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        tempCall_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloTemperatureProto.internal_static_TemperatureRequest_descriptor;
      }

      @Override
      public TemperatureRequest getDefaultInstanceForType() {
        return TemperatureRequest.getDefaultInstance();
      }

      @Override
      public TemperatureRequest build() {
        TemperatureRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TemperatureRequest buildPartial() {
        TemperatureRequest result = new TemperatureRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TemperatureRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.tempCall_ = tempCall_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TemperatureRequest) {
          return mergeFrom((TemperatureRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TemperatureRequest other) {
        if (other == TemperatureRequest.getDefaultInstance()) return this;
        if (!other.getTempCall().isEmpty()) {
          tempCall_ = other.tempCall_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                tempCall_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object tempCall_ = "";
      /**
       * <code>string tempCall = 1;</code>
       * @return The tempCall.
       */
      public String getTempCall() {
        Object ref = tempCall_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tempCall_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tempCall = 1;</code>
       * @return The bytes for tempCall.
       */
      public com.google.protobuf.ByteString
          getTempCallBytes() {
        Object ref = tempCall_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tempCall_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tempCall = 1;</code>
       * @param value The tempCall to set.
       * @return This builder for chaining.
       */
      public Builder setTempCall(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        tempCall_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string tempCall = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTempCall() {
        tempCall_ = getDefaultInstance().getTempCall();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string tempCall = 1;</code>
       * @param value The bytes for tempCall to set.
       * @return This builder for chaining.
       */
      public Builder setTempCallBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        tempCall_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TemperatureRequest)
    }

    // @@protoc_insertion_point(class_scope:TemperatureRequest)
    private static final TemperatureRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TemperatureRequest();
    }

    public static TemperatureRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TemperatureRequest>
        PARSER = new com.google.protobuf.AbstractParser<TemperatureRequest>() {
      @Override
      public TemperatureRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TemperatureRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TemperatureRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public TemperatureRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TemperatureResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TemperatureResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string homeArea = 1;</code>
     * @return The homeArea.
     */
    String getHomeArea();
    /**
     * <code>string homeArea = 1;</code>
     * @return The bytes for homeArea.
     */
    com.google.protobuf.ByteString
        getHomeAreaBytes();

    /**
     * <code>double degreeCelsius = 2;</code>
     * @return The degreeCelsius.
     */
    double getDegreeCelsius();
  }
  /**
   * Protobuf type {@code TemperatureResponse}
   */
  public static final class TemperatureResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TemperatureResponse)
      TemperatureResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TemperatureResponse.newBuilder() to construct.
    private TemperatureResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TemperatureResponse() {
      homeArea_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TemperatureResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloTemperatureProto.internal_static_TemperatureResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloTemperatureProto.internal_static_TemperatureResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TemperatureResponse.class, Builder.class);
    }

    public static final int HOMEAREA_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object homeArea_ = "";
    /**
     * <code>string homeArea = 1;</code>
     * @return The homeArea.
     */
    @Override
    public String getHomeArea() {
      Object ref = homeArea_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        homeArea_ = s;
        return s;
      }
    }
    /**
     * <code>string homeArea = 1;</code>
     * @return The bytes for homeArea.
     */
    @Override
    public com.google.protobuf.ByteString
        getHomeAreaBytes() {
      Object ref = homeArea_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        homeArea_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEGREECELSIUS_FIELD_NUMBER = 2;
    private double degreeCelsius_ = 0D;
    /**
     * <code>double degreeCelsius = 2;</code>
     * @return The degreeCelsius.
     */
    @Override
    public double getDegreeCelsius() {
      return degreeCelsius_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeArea_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, homeArea_);
      }
      if (Double.doubleToRawLongBits(degreeCelsius_) != 0) {
        output.writeDouble(2, degreeCelsius_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(homeArea_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, homeArea_);
      }
      if (Double.doubleToRawLongBits(degreeCelsius_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, degreeCelsius_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TemperatureResponse)) {
        return super.equals(obj);
      }
      TemperatureResponse other = (TemperatureResponse) obj;

      if (!getHomeArea()
          .equals(other.getHomeArea())) return false;
      if (Double.doubleToLongBits(getDegreeCelsius())
          != Double.doubleToLongBits(
              other.getDegreeCelsius())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HOMEAREA_FIELD_NUMBER;
      hash = (53 * hash) + getHomeArea().hashCode();
      hash = (37 * hash) + DEGREECELSIUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDegreeCelsius()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TemperatureResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemperatureResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemperatureResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemperatureResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemperatureResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TemperatureResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TemperatureResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TemperatureResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static TemperatureResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static TemperatureResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TemperatureResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TemperatureResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TemperatureResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TemperatureResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TemperatureResponse)
        TemperatureResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloTemperatureProto.internal_static_TemperatureResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloTemperatureProto.internal_static_TemperatureResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TemperatureResponse.class, Builder.class);
      }

      // Construct using com.temperature.HelloTemperatureProto.TemperatureResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        homeArea_ = "";
        degreeCelsius_ = 0D;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloTemperatureProto.internal_static_TemperatureResponse_descriptor;
      }

      @Override
      public TemperatureResponse getDefaultInstanceForType() {
        return TemperatureResponse.getDefaultInstance();
      }

      @Override
      public TemperatureResponse build() {
        TemperatureResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TemperatureResponse buildPartial() {
        TemperatureResponse result = new TemperatureResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(TemperatureResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.homeArea_ = homeArea_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.degreeCelsius_ = degreeCelsius_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TemperatureResponse) {
          return mergeFrom((TemperatureResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TemperatureResponse other) {
        if (other == TemperatureResponse.getDefaultInstance()) return this;
        if (!other.getHomeArea().isEmpty()) {
          homeArea_ = other.homeArea_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getDegreeCelsius() != 0D) {
          setDegreeCelsius(other.getDegreeCelsius());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                homeArea_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                degreeCelsius_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object homeArea_ = "";
      /**
       * <code>string homeArea = 1;</code>
       * @return The homeArea.
       */
      public String getHomeArea() {
        Object ref = homeArea_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          homeArea_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string homeArea = 1;</code>
       * @return The bytes for homeArea.
       */
      public com.google.protobuf.ByteString
          getHomeAreaBytes() {
        Object ref = homeArea_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          homeArea_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string homeArea = 1;</code>
       * @param value The homeArea to set.
       * @return This builder for chaining.
       */
      public Builder setHomeArea(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        homeArea_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string homeArea = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHomeArea() {
        homeArea_ = getDefaultInstance().getHomeArea();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string homeArea = 1;</code>
       * @param value The bytes for homeArea to set.
       * @return This builder for chaining.
       */
      public Builder setHomeAreaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        homeArea_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double degreeCelsius_ ;
      /**
       * <code>double degreeCelsius = 2;</code>
       * @return The degreeCelsius.
       */
      @Override
      public double getDegreeCelsius() {
        return degreeCelsius_;
      }
      /**
       * <code>double degreeCelsius = 2;</code>
       * @param value The degreeCelsius to set.
       * @return This builder for chaining.
       */
      public Builder setDegreeCelsius(double value) {

        degreeCelsius_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double degreeCelsius = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDegreeCelsius() {
        bitField0_ = (bitField0_ & ~0x00000002);
        degreeCelsius_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TemperatureResponse)
    }

    // @@protoc_insertion_point(class_scope:TemperatureResponse)
    private static final TemperatureResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TemperatureResponse();
    }

    public static TemperatureResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TemperatureResponse>
        PARSER = new com.google.protobuf.AbstractParser<TemperatureResponse>() {
      @Override
      public TemperatureResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TemperatureResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TemperatureResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public TemperatureResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TemperatureResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021Temperature.proto\"&\n\022TemperatureReques" +
      "t\022\020\n\010tempCall\030\001 \001(\t\">\n\023TemperatureRespon" +
      "se\022\020\n\010homeArea\030\001 \001(\t\022\025\n\rdegreeCelsius\030\002 " +
      "\001(\0012U\n\020HelloTemperature\022A\n\022temperatureSe" +
      "rvice\022\023.TemperatureRequest\032\024.Temperature" +
      "Response0\001B*\n\017com.temperatureB\025HelloTemp" +
      "eratureProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureRequest_descriptor,
        new String[] { "TempCall", });
    internal_static_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TemperatureResponse_descriptor,
        new String[] { "HomeArea", "DegreeCelsius", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
