// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Appliance.proto

// Protobuf Java Version: 3.25.1
package com.appliance;

public final class HelloApplianceProto {
  private HelloApplianceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApplianceRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApplianceRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string applianceName = 1;</code>
     * @return The applianceName.
     */
    String getApplianceName();
    /**
     * <code>string applianceName = 1;</code>
     * @return The bytes for applianceName.
     */
    com.google.protobuf.ByteString
        getApplianceNameBytes();

    /**
     * <code>string applianceOperation = 2;</code>
     * @return The applianceOperation.
     */
    String getApplianceOperation();
    /**
     * <code>string applianceOperation = 2;</code>
     * @return The bytes for applianceOperation.
     */
    com.google.protobuf.ByteString
        getApplianceOperationBytes();
  }
  /**
   * Protobuf type {@code ApplianceRequest}
   */
  public static final class ApplianceRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApplianceRequest)
      ApplianceRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplianceRequest.newBuilder() to construct.
    private ApplianceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplianceRequest() {
      applianceName_ = "";
      applianceOperation_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplianceRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloApplianceProto.internal_static_ApplianceRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloApplianceProto.internal_static_ApplianceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ApplianceRequest.class, Builder.class);
    }

    public static final int APPLIANCENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object applianceName_ = "";
    /**
     * <code>string applianceName = 1;</code>
     * @return The applianceName.
     */
    @Override
    public String getApplianceName() {
      Object ref = applianceName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        applianceName_ = s;
        return s;
      }
    }
    /**
     * <code>string applianceName = 1;</code>
     * @return The bytes for applianceName.
     */
    @Override
    public com.google.protobuf.ByteString
        getApplianceNameBytes() {
      Object ref = applianceName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        applianceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPLIANCEOPERATION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object applianceOperation_ = "";
    /**
     * <code>string applianceOperation = 2;</code>
     * @return The applianceOperation.
     */
    @Override
    public String getApplianceOperation() {
      Object ref = applianceOperation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        applianceOperation_ = s;
        return s;
      }
    }
    /**
     * <code>string applianceOperation = 2;</code>
     * @return The bytes for applianceOperation.
     */
    @Override
    public com.google.protobuf.ByteString
        getApplianceOperationBytes() {
      Object ref = applianceOperation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        applianceOperation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(applianceName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, applianceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(applianceOperation_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, applianceOperation_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(applianceName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, applianceName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(applianceOperation_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, applianceOperation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ApplianceRequest)) {
        return super.equals(obj);
      }
      ApplianceRequest other = (ApplianceRequest) obj;

      if (!getApplianceName()
          .equals(other.getApplianceName())) return false;
      if (!getApplianceOperation()
          .equals(other.getApplianceOperation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + APPLIANCENAME_FIELD_NUMBER;
      hash = (53 * hash) + getApplianceName().hashCode();
      hash = (37 * hash) + APPLIANCEOPERATION_FIELD_NUMBER;
      hash = (53 * hash) + getApplianceOperation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ApplianceRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplianceRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplianceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplianceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplianceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplianceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplianceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ApplianceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ApplianceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ApplianceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ApplianceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ApplianceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApplianceRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApplianceRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApplianceRequest)
        ApplianceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloApplianceProto.internal_static_ApplianceRequest_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloApplianceProto.internal_static_ApplianceRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ApplianceRequest.class, Builder.class);
      }

      // Construct using com.appliance.HelloApplianceProto.ApplianceRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        applianceName_ = "";
        applianceOperation_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloApplianceProto.internal_static_ApplianceRequest_descriptor;
      }

      @Override
      public ApplianceRequest getDefaultInstanceForType() {
        return ApplianceRequest.getDefaultInstance();
      }

      @Override
      public ApplianceRequest build() {
        ApplianceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ApplianceRequest buildPartial() {
        ApplianceRequest result = new ApplianceRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ApplianceRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.applianceName_ = applianceName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.applianceOperation_ = applianceOperation_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ApplianceRequest) {
          return mergeFrom((ApplianceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ApplianceRequest other) {
        if (other == ApplianceRequest.getDefaultInstance()) return this;
        if (!other.getApplianceName().isEmpty()) {
          applianceName_ = other.applianceName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getApplianceOperation().isEmpty()) {
          applianceOperation_ = other.applianceOperation_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                applianceName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                applianceOperation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object applianceName_ = "";
      /**
       * <code>string applianceName = 1;</code>
       * @return The applianceName.
       */
      public String getApplianceName() {
        Object ref = applianceName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          applianceName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string applianceName = 1;</code>
       * @return The bytes for applianceName.
       */
      public com.google.protobuf.ByteString
          getApplianceNameBytes() {
        Object ref = applianceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          applianceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string applianceName = 1;</code>
       * @param value The applianceName to set.
       * @return This builder for chaining.
       */
      public Builder setApplianceName(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        applianceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string applianceName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplianceName() {
        applianceName_ = getDefaultInstance().getApplianceName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string applianceName = 1;</code>
       * @param value The bytes for applianceName to set.
       * @return This builder for chaining.
       */
      public Builder setApplianceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        applianceName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object applianceOperation_ = "";
      /**
       * <code>string applianceOperation = 2;</code>
       * @return The applianceOperation.
       */
      public String getApplianceOperation() {
        Object ref = applianceOperation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          applianceOperation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string applianceOperation = 2;</code>
       * @return The bytes for applianceOperation.
       */
      public com.google.protobuf.ByteString
          getApplianceOperationBytes() {
        Object ref = applianceOperation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          applianceOperation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string applianceOperation = 2;</code>
       * @param value The applianceOperation to set.
       * @return This builder for chaining.
       */
      public Builder setApplianceOperation(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        applianceOperation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string applianceOperation = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearApplianceOperation() {
        applianceOperation_ = getDefaultInstance().getApplianceOperation();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string applianceOperation = 2;</code>
       * @param value The bytes for applianceOperation to set.
       * @return This builder for chaining.
       */
      public Builder setApplianceOperationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        applianceOperation_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ApplianceRequest)
    }

    // @@protoc_insertion_point(class_scope:ApplianceRequest)
    private static final ApplianceRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApplianceRequest();
    }

    public static ApplianceRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplianceRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApplianceRequest>() {
      @Override
      public ApplianceRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApplianceRequest> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ApplianceRequest> getParserForType() {
      return PARSER;
    }

    @Override
    public ApplianceRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApplianceResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ApplianceResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string operationResponse = 1;</code>
     * @return The operationResponse.
     */
    String getOperationResponse();
    /**
     * <code>string operationResponse = 1;</code>
     * @return The bytes for operationResponse.
     */
    com.google.protobuf.ByteString
        getOperationResponseBytes();
  }
  /**
   * Protobuf type {@code ApplianceResponse}
   */
  public static final class ApplianceResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ApplianceResponse)
      ApplianceResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApplianceResponse.newBuilder() to construct.
    private ApplianceResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApplianceResponse() {
      operationResponse_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new ApplianceResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HelloApplianceProto.internal_static_ApplianceResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HelloApplianceProto.internal_static_ApplianceResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ApplianceResponse.class, Builder.class);
    }

    public static final int OPERATIONRESPONSE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object operationResponse_ = "";
    /**
     * <code>string operationResponse = 1;</code>
     * @return The operationResponse.
     */
    @Override
    public String getOperationResponse() {
      Object ref = operationResponse_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        operationResponse_ = s;
        return s;
      }
    }
    /**
     * <code>string operationResponse = 1;</code>
     * @return The bytes for operationResponse.
     */
    @Override
    public com.google.protobuf.ByteString
        getOperationResponseBytes() {
      Object ref = operationResponse_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        operationResponse_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationResponse_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, operationResponse_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(operationResponse_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, operationResponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ApplianceResponse)) {
        return super.equals(obj);
      }
      ApplianceResponse other = (ApplianceResponse) obj;

      if (!getOperationResponse()
          .equals(other.getOperationResponse())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OPERATIONRESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getOperationResponse().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ApplianceResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplianceResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplianceResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplianceResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplianceResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ApplianceResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ApplianceResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ApplianceResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ApplianceResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ApplianceResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ApplianceResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ApplianceResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ApplianceResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApplianceResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ApplianceResponse)
        ApplianceResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HelloApplianceProto.internal_static_ApplianceResponse_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HelloApplianceProto.internal_static_ApplianceResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ApplianceResponse.class, Builder.class);
      }

      // Construct using com.appliance.HelloApplianceProto.ApplianceResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        operationResponse_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HelloApplianceProto.internal_static_ApplianceResponse_descriptor;
      }

      @Override
      public ApplianceResponse getDefaultInstanceForType() {
        return ApplianceResponse.getDefaultInstance();
      }

      @Override
      public ApplianceResponse build() {
        ApplianceResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ApplianceResponse buildPartial() {
        ApplianceResponse result = new ApplianceResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ApplianceResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.operationResponse_ = operationResponse_;
        }
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ApplianceResponse) {
          return mergeFrom((ApplianceResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ApplianceResponse other) {
        if (other == ApplianceResponse.getDefaultInstance()) return this;
        if (!other.getOperationResponse().isEmpty()) {
          operationResponse_ = other.operationResponse_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                operationResponse_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object operationResponse_ = "";
      /**
       * <code>string operationResponse = 1;</code>
       * @return The operationResponse.
       */
      public String getOperationResponse() {
        Object ref = operationResponse_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          operationResponse_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string operationResponse = 1;</code>
       * @return The bytes for operationResponse.
       */
      public com.google.protobuf.ByteString
          getOperationResponseBytes() {
        Object ref = operationResponse_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          operationResponse_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string operationResponse = 1;</code>
       * @param value The operationResponse to set.
       * @return This builder for chaining.
       */
      public Builder setOperationResponse(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        operationResponse_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string operationResponse = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOperationResponse() {
        operationResponse_ = getDefaultInstance().getOperationResponse();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string operationResponse = 1;</code>
       * @param value The bytes for operationResponse to set.
       * @return This builder for chaining.
       */
      public Builder setOperationResponseBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        operationResponse_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ApplianceResponse)
    }

    // @@protoc_insertion_point(class_scope:ApplianceResponse)
    private static final ApplianceResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ApplianceResponse();
    }

    public static ApplianceResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApplianceResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApplianceResponse>() {
      @Override
      public ApplianceResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ApplianceResponse> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ApplianceResponse> getParserForType() {
      return PARSER;
    }

    @Override
    public ApplianceResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplianceRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApplianceRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ApplianceResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ApplianceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Appliance.proto\"E\n\020ApplianceRequest\022\025\n" +
      "\rapplianceName\030\001 \001(\t\022\032\n\022applianceOperati" +
      "on\030\002 \001(\t\".\n\021ApplianceResponse\022\031\n\021operati" +
      "onResponse\030\001 \001(\t2M\n\016HelloAppliance\022;\n\020ap" +
      "plianceService\022\021.ApplianceRequest\032\022.Appl" +
      "ianceResponse(\001B&\n\rcom.applianceB\023HelloA" +
      "pplianceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ApplianceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ApplianceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApplianceRequest_descriptor,
        new String[] { "ApplianceName", "ApplianceOperation", });
    internal_static_ApplianceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ApplianceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ApplianceResponse_descriptor,
        new String[] { "OperationResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
